// ═══════════════════════════════════════════════════════════════
// KoreHan Vocabulary Bank — Real TOPIK-based words
// 375 words: 125 Beginner + 125 Intermediate + 125 Advanced
// ═══════════════════════════════════════════════════════════════
(function() {
  var BEGINNER = [
    {word_ko:'나',word_rom:'na',word_en:'I, me'},
    {word_ko:'우리',word_rom:'u-ri',word_en:'we, us'},
    {word_ko:'사람',word_rom:'sa-ram',word_en:'person'},
    {word_ko:'이름',word_rom:'i-reum',word_en:'name'},
    {word_ko:'친구',word_rom:'chin-gu',word_en:'friend'},
    {word_ko:'가족',word_rom:'ga-jok',word_en:'family'},
    {word_ko:'아버지',word_rom:'a-beo-ji',word_en:'father'},
    {word_ko:'어머니',word_rom:'eo-meo-ni',word_en:'mother'},
    {word_ko:'동생',word_rom:'dong-saeng',word_en:'younger sibling'},
    {word_ko:'아이',word_rom:'a-i',word_en:'child'},
    {word_ko:'남자',word_rom:'nam-ja',word_en:'man'},
    {word_ko:'여자',word_rom:'yeo-ja',word_en:'woman'},
    {word_ko:'선생님',word_rom:'seon-saeng-nim',word_en:'teacher'},
    {word_ko:'학생',word_rom:'hak-saeng',word_en:'student'},
    {word_ko:'집',word_rom:'jip',word_en:'house, home'},
    {word_ko:'학교',word_rom:'hak-gyo',word_en:'school'},
    {word_ko:'회사',word_rom:'hoe-sa',word_en:'company'},
    {word_ko:'식당',word_rom:'sik-dang',word_en:'restaurant'},
    {word_ko:'병원',word_rom:'byeong-won',word_en:'hospital'},
    {word_ko:'은행',word_rom:'eun-haeng',word_en:'bank'},
    {word_ko:'공원',word_rom:'gong-won',word_en:'park'},
    {word_ko:'역',word_rom:'yeok',word_en:'station'},
    {word_ko:'도서관',word_rom:'do-seo-gwan',word_en:'library'},
    {word_ko:'화장실',word_rom:'hwa-jang-sil',word_en:'bathroom'},
    {word_ko:'밥',word_rom:'bap',word_en:'rice, meal'},
    {word_ko:'물',word_rom:'mul',word_en:'water'},
    {word_ko:'고기',word_rom:'go-gi',word_en:'meat'},
    {word_ko:'야채',word_rom:'ya-chae',word_en:'vegetable'},
    {word_ko:'과일',word_rom:'gwa-il',word_en:'fruit'},
    {word_ko:'커피',word_rom:'keo-pi',word_en:'coffee'},
    {word_ko:'김치',word_rom:'gim-chi',word_en:'kimchi'},
    {word_ko:'라면',word_rom:'ra-myeon',word_en:'ramen'},
    {word_ko:'오늘',word_rom:'o-neul',word_en:'today'},
    {word_ko:'내일',word_rom:'nae-il',word_en:'tomorrow'},
    {word_ko:'어제',word_rom:'eo-je',word_en:'yesterday'},
    {word_ko:'지금',word_rom:'ji-geum',word_en:'now'},
    {word_ko:'아침',word_rom:'a-chim',word_en:'morning'},
    {word_ko:'저녁',word_rom:'jeo-nyeok',word_en:'evening'},
    {word_ko:'밤',word_rom:'bam',word_en:'night'},
    {word_ko:'시간',word_rom:'si-gan',word_en:'time, hour'},
    {word_ko:'주말',word_rom:'ju-mal',word_en:'weekend'},
    {word_ko:'날씨',word_rom:'nal-ssi',word_en:'weather'},
    {word_ko:'봄',word_rom:'bom',word_en:'spring'},
    {word_ko:'여름',word_rom:'yeo-reum',word_en:'summer'},
    {word_ko:'겨울',word_rom:'gyeo-ul',word_en:'winter'},
    {word_ko:'비',word_rom:'bi',word_en:'rain'},
    {word_ko:'눈',word_rom:'nun',word_en:'snow; eye'},
    {word_ko:'하다',word_rom:'ha-da',word_en:'to do'},
    {word_ko:'가다',word_rom:'ga-da',word_en:'to go'},
    {word_ko:'오다',word_rom:'o-da',word_en:'to come'},
    {word_ko:'보다',word_rom:'bo-da',word_en:'to see, watch'},
    {word_ko:'먹다',word_rom:'meok-da',word_en:'to eat'},
    {word_ko:'마시다',word_rom:'ma-si-da',word_en:'to drink'},
    {word_ko:'읽다',word_rom:'ik-da',word_en:'to read'},
    {word_ko:'쓰다',word_rom:'sseu-da',word_en:'to write'},
    {word_ko:'듣다',word_rom:'deut-da',word_en:'to listen'},
    {word_ko:'말하다',word_rom:'mal-ha-da',word_en:'to speak'},
    {word_ko:'사다',word_rom:'sa-da',word_en:'to buy'},
    {word_ko:'주다',word_rom:'ju-da',word_en:'to give'},
    {word_ko:'받다',word_rom:'bat-da',word_en:'to receive'},
    {word_ko:'만나다',word_rom:'man-na-da',word_en:'to meet'},
    {word_ko:'알다',word_rom:'al-da',word_en:'to know'},
    {word_ko:'좋아하다',word_rom:'jo-a-ha-da',word_en:'to like'},
    {word_ko:'있다',word_rom:'it-da',word_en:'to exist, have'},
    {word_ko:'없다',word_rom:'eop-da',word_en:'to not exist'},
    {word_ko:'살다',word_rom:'sal-da',word_en:'to live'},
    {word_ko:'자다',word_rom:'ja-da',word_en:'to sleep'},
    {word_ko:'일어나다',word_rom:'i-reo-na-da',word_en:'to wake up'},
    {word_ko:'걷다',word_rom:'geot-da',word_en:'to walk'},
    {word_ko:'일하다',word_rom:'il-ha-da',word_en:'to work'},
    {word_ko:'공부하다',word_rom:'gong-bu-ha-da',word_en:'to study'},
    {word_ko:'배우다',word_rom:'bae-u-da',word_en:'to learn'},
    {word_ko:'기다리다',word_rom:'gi-da-ri-da',word_en:'to wait'},
    {word_ko:'쉬다',word_rom:'swi-da',word_en:'to rest'},
    {word_ko:'운동하다',word_rom:'un-dong-ha-da',word_en:'to exercise'},
    {word_ko:'좋다',word_rom:'jo-ta',word_en:'good'},
    {word_ko:'크다',word_rom:'keu-da',word_en:'big'},
    {word_ko:'작다',word_rom:'jak-da',word_en:'small'},
    {word_ko:'많다',word_rom:'man-ta',word_en:'many'},
    {word_ko:'비싸다',word_rom:'bi-ssa-da',word_en:'expensive'},
    {word_ko:'맛있다',word_rom:'ma-sit-da',word_en:'delicious'},
    {word_ko:'예쁘다',word_rom:'ye-ppeu-da',word_en:'pretty'},
    {word_ko:'빠르다',word_rom:'ppa-reu-da',word_en:'fast'},
    {word_ko:'쉽다',word_rom:'swip-da',word_en:'easy'},
    {word_ko:'어렵다',word_rom:'eo-ryeop-da',word_en:'difficult'},
    {word_ko:'재미있다',word_rom:'jae-mi-it-da',word_en:'fun, interesting'},
    {word_ko:'피곤하다',word_rom:'pi-gon-ha-da',word_en:'tired'},
    {word_ko:'바쁘다',word_rom:'ba-ppeu-da',word_en:'busy'},
    {word_ko:'행복하다',word_rom:'haeng-bok-ha-da',word_en:'happy'},
    {word_ko:'배고프다',word_rom:'bae-go-peu-da',word_en:'hungry'},
    {word_ko:'옷',word_rom:'ot',word_en:'clothes'},
    {word_ko:'신발',word_rom:'sin-bal',word_en:'shoes'},
    {word_ko:'가방',word_rom:'ga-bang',word_en:'bag'},
    {word_ko:'휴대폰',word_rom:'hyu-dae-pon',word_en:'cellphone'},
    {word_ko:'책',word_rom:'chaek',word_en:'book'},
    {word_ko:'의자',word_rom:'ui-ja',word_en:'chair'},
    {word_ko:'버스',word_rom:'beo-seu',word_en:'bus'},
    {word_ko:'지하철',word_rom:'ji-ha-cheol',word_en:'subway'},
    {word_ko:'택시',word_rom:'taek-si',word_en:'taxi'},
    {word_ko:'길',word_rom:'gil',word_en:'road, way'},
    {word_ko:'왼쪽',word_rom:'oen-jjok',word_en:'left'},
    {word_ko:'오른쪽',word_rom:'o-reun-jjok',word_en:'right'},
    {word_ko:'한국',word_rom:'han-guk',word_en:'Korea'},
    {word_ko:'한국어',word_rom:'han-guk-eo',word_en:'Korean language'},
    {word_ko:'돈',word_rom:'don',word_en:'money'},
    {word_ko:'사진',word_rom:'sa-jin',word_en:'photo'},
    {word_ko:'음악',word_rom:'eum-ak',word_en:'music'},
    {word_ko:'영화',word_rom:'yeong-hwa',word_en:'movie'},
    {word_ko:'여행',word_rom:'yeo-haeng',word_en:'travel'},
    {word_ko:'선물',word_rom:'seon-mul',word_en:'gift'},
    {word_ko:'생일',word_rom:'saeng-il',word_en:'birthday'},
    {word_ko:'약속',word_rom:'yak-sok',word_en:'appointment'},
    {word_ko:'사랑',word_rom:'sa-rang',word_en:'love'},
    {word_ko:'건강',word_rom:'geon-gang',word_en:'health'},
    {word_ko:'산',word_rom:'san',word_en:'mountain'},
    {word_ko:'바다',word_rom:'ba-da',word_en:'sea'},
    {word_ko:'꽃',word_rom:'kkot',word_en:'flower'},
    {word_ko:'동물',word_rom:'dong-mul',word_en:'animal'},
    {word_ko:'개',word_rom:'gae',word_en:'dog'},
    {word_ko:'고양이',word_rom:'go-yang-i',word_en:'cat'},
    {word_ko:'마음',word_rom:'ma-eum',word_en:'heart, mind'},
    {word_ko:'생각',word_rom:'saeng-gak',word_en:'thought'},
    {word_ko:'정말',word_rom:'jeong-mal',word_en:'really'},
    {word_ko:'많이',word_rom:'ma-ni',word_en:'a lot'},
    {word_ko:'항상',word_rom:'hang-sang',word_en:'always'},
    {word_ko:'왜',word_rom:'wae',word_en:'why'},
    {word_ko:'어디',word_rom:'eo-di',word_en:'where'},
    {word_ko:'언제',word_rom:'eon-je',word_en:'when'},
    {word_ko:'누구',word_rom:'nu-gu',word_en:'who'},
    {word_ko:'어떻게',word_rom:'eo-tteo-ke',word_en:'how'},
    {word_ko:'네',word_rom:'ne',word_en:'yes'},
    {word_ko:'아니요',word_rom:'a-ni-yo',word_en:'no'},
    {word_ko:'우유',word_rom:'u-yu',word_en:'milk'},
    {word_ko:'빵',word_rom:'ppang',word_en:'bread'},
    {word_ko:'계란',word_rom:'gye-ran',word_en:'egg'},
    {word_ko:'치킨',word_rom:'chi-kin',word_en:'chicken'},
    {word_ko:'떡볶이',word_rom:'tteok-bokk-i',word_en:'tteokbokki'},
    {word_ko:'냉면',word_rom:'naeng-myeon',word_en:'cold noodles'},
    {word_ko:'삼겹살',word_rom:'sam-gyeop-sal',word_en:'pork belly'},
    {word_ko:'된장찌개',word_rom:'doen-jang-jji-gae',word_en:'soybean paste stew'},
    {word_ko:'오빠',word_rom:'o-ppa',word_en:'older brother (female)'},
    {word_ko:'언니',word_rom:'eon-ni',word_en:'older sister (female)'},
    {word_ko:'형',word_rom:'hyeong',word_en:'older brother (male)'},
    {word_ko:'누나',word_rom:'nu-na',word_en:'older sister (male)'},
    {word_ko:'할머니',word_rom:'hal-meo-ni',word_en:'grandmother'},
    {word_ko:'할아버지',word_rom:'hal-a-beo-ji',word_en:'grandfather'},
    {word_ko:'노래',word_rom:'no-rae',word_en:'song'},
    {word_ko:'춤',word_rom:'chum',word_en:'dance'},
    {word_ko:'게임',word_rom:'ge-im',word_en:'game'},
    {word_ko:'그림',word_rom:'geu-rim',word_en:'picture, drawing'},
    {word_ko:'편지',word_rom:'pyeon-ji',word_en:'letter'},
    {word_ko:'요리',word_rom:'yo-ri',word_en:'cooking, dish'},
    {word_ko:'비행기',word_rom:'bi-haeng-gi',word_en:'airplane'},
    {word_ko:'배',word_rom:'bae',word_en:'stomach; boat; pear'},
    {word_ko:'다리',word_rom:'da-ri',word_en:'leg; bridge'},
    {word_ko:'머리',word_rom:'meo-ri',word_en:'head, hair'},
    {word_ko:'손',word_rom:'son',word_en:'hand'},
    {word_ko:'발',word_rom:'bal',word_en:'foot'},
    {word_ko:'입',word_rom:'ip',word_en:'mouth'},
    {word_ko:'코',word_rom:'ko',word_en:'nose'},
    {word_ko:'귀',word_rom:'gwi',word_en:'ear'},
    {word_ko:'나이',word_rom:'na-i',word_en:'age'},
    {word_ko:'결혼',word_rom:'gyeol-hon',word_en:'marriage'},
    {word_ko:'인사',word_rom:'in-sa',word_en:'greeting'},
    {word_ko:'감사',word_rom:'gam-sa',word_en:'thanks'},
    {word_ko:'축구',word_rom:'chuk-gu',word_en:'soccer'},
    {word_ko:'야구',word_rom:'ya-gu',word_en:'baseball'},
    {word_ko:'수영',word_rom:'su-yeong',word_en:'swimming'},
    {word_ko:'등산',word_rom:'deung-san',word_en:'hiking'},
    {word_ko:'나무',word_rom:'na-mu',word_en:'tree'},
    {word_ko:'강',word_rom:'gang',word_en:'river'},
    {word_ko:'새',word_rom:'sae',word_en:'bird'},
    {word_ko:'침대',word_rom:'chim-dae',word_en:'bed'},
    {word_ko:'창문',word_rom:'chang-mun',word_en:'window'},
    {word_ko:'컴퓨터',word_rom:'keom-pyu-teo',word_en:'computer'}
  ];

  var INTERMEDIATE = [
    {word_ko:'경험',word_rom:'gyeong-heom',word_en:'experience'},
    {word_ko:'관계',word_rom:'gwan-gye',word_en:'relationship'},
    {word_ko:'관심',word_rom:'gwan-sim',word_en:'interest'},
    {word_ko:'교육',word_rom:'gyo-yuk',word_en:'education'},
    {word_ko:'기회',word_rom:'gi-hoe',word_en:'opportunity'},
    {word_ko:'노력',word_rom:'no-ryeok',word_en:'effort'},
    {word_ko:'능력',word_rom:'neung-ryeok',word_en:'ability'},
    {word_ko:'대화',word_rom:'dae-hwa',word_en:'conversation'},
    {word_ko:'목표',word_rom:'mok-pyo',word_en:'goal'},
    {word_ko:'문화',word_rom:'mun-hwa',word_en:'culture'},
    {word_ko:'방법',word_rom:'bang-beop',word_en:'method, way'},
    {word_ko:'변화',word_rom:'byeon-hwa',word_en:'change'},
    {word_ko:'사건',word_rom:'sa-geon',word_en:'incident, event'},
    {word_ko:'사실',word_rom:'sa-sil',word_en:'fact, truth'},
    {word_ko:'상황',word_rom:'sang-hwang',word_en:'situation'},
    {word_ko:'선택',word_rom:'seon-taek',word_en:'choice'},
    {word_ko:'성격',word_rom:'seong-gyeok',word_en:'personality'},
    {word_ko:'소식',word_rom:'so-sik',word_en:'news, word'},
    {word_ko:'습관',word_rom:'seup-gwan',word_en:'habit'},
    {word_ko:'시작',word_rom:'si-jak',word_en:'start, beginning'},
    {word_ko:'실수',word_rom:'sil-su',word_en:'mistake'},
    {word_ko:'약',word_rom:'yak',word_en:'medicine'},
    {word_ko:'역사',word_rom:'yeok-sa',word_en:'history'},
    {word_ko:'연습',word_rom:'yeon-seup',word_en:'practice'},
    {word_ko:'예절',word_rom:'ye-jeol',word_en:'manners, etiquette'},
    {word_ko:'원인',word_rom:'won-in',word_en:'cause'},
    {word_ko:'의견',word_rom:'ui-gyeon',word_en:'opinion'},
    {word_ko:'이유',word_rom:'i-yu',word_en:'reason'},
    {word_ko:'인구',word_rom:'in-gu',word_en:'population'},
    {word_ko:'자신',word_rom:'ja-sin',word_en:'oneself'},
    {word_ko:'자연',word_rom:'ja-yeon',word_en:'nature'},
    {word_ko:'전통',word_rom:'jeon-tong',word_en:'tradition'},
    {word_ko:'정보',word_rom:'jeong-bo',word_en:'information'},
    {word_ko:'조건',word_rom:'jo-geon',word_en:'condition'},
    {word_ko:'준비',word_rom:'jun-bi',word_en:'preparation'},
    {word_ko:'지식',word_rom:'ji-sik',word_en:'knowledge'},
    {word_ko:'직업',word_rom:'jik-eop',word_en:'occupation'},
    {word_ko:'차이',word_rom:'cha-i',word_en:'difference'},
    {word_ko:'태도',word_rom:'tae-do',word_en:'attitude'},
    {word_ko:'표현',word_rom:'pyo-hyeon',word_en:'expression'},
    {word_ko:'환경',word_rom:'hwan-gyeong',word_en:'environment'},
    {word_ko:'효과',word_rom:'hyo-gwa',word_en:'effect'},
    {word_ko:'결과',word_rom:'gyeol-gwa',word_en:'result'},
    {word_ko:'과정',word_rom:'gwa-jeong',word_en:'process'},
    {word_ko:'규칙',word_rom:'gyu-chik',word_en:'rule'},
    {word_ko:'기술',word_rom:'gi-sul',word_en:'technology, skill'},
    {word_ko:'경제',word_rom:'gyeong-je',word_en:'economy'},
    {word_ko:'계획',word_rom:'gye-hoek',word_en:'plan'},
    {word_ko:'구체적',word_rom:'gu-che-jeok',word_en:'specific'},
    {word_ko:'긍정적',word_rom:'geung-jeong-jeok',word_en:'positive'},
    {word_ko:'갑자기',word_rom:'gap-ja-gi',word_en:'suddenly'},
    {word_ko:'나타나다',word_rom:'na-ta-na-da',word_en:'to appear'},
    {word_ko:'놀라다',word_rom:'nol-la-da',word_en:'to be surprised'},
    {word_ko:'느끼다',word_rom:'neu-kki-da',word_en:'to feel'},
    {word_ko:'다르다',word_rom:'da-reu-da',word_en:'to be different'},
    {word_ko:'닮다',word_rom:'dam-da',word_en:'to resemble'},
    {word_ko:'떨어지다',word_rom:'tteo-reo-ji-da',word_en:'to fall, drop'},
    {word_ko:'모이다',word_rom:'mo-i-da',word_en:'to gather'},
    {word_ko:'믿다',word_rom:'mit-da',word_en:'to believe'},
    {word_ko:'바꾸다',word_rom:'ba-kku-da',word_en:'to change, exchange'},
    {word_ko:'발견하다',word_rom:'bal-gyeon-ha-da',word_en:'to discover'},
    {word_ko:'비교하다',word_rom:'bi-gyo-ha-da',word_en:'to compare'},
    {word_ko:'설명하다',word_rom:'seol-myeong-ha-da',word_en:'to explain'},
    {word_ko:'성공하다',word_rom:'seong-gong-ha-da',word_en:'to succeed'},
    {word_ko:'실패하다',word_rom:'sil-pae-ha-da',word_en:'to fail'},
    {word_ko:'이해하다',word_rom:'i-hae-ha-da',word_en:'to understand'},
    {word_ko:'참다',word_rom:'cham-da',word_en:'to endure'},
    {word_ko:'참여하다',word_rom:'cham-yeo-ha-da',word_en:'to participate'},
    {word_ko:'포기하다',word_rom:'po-gi-ha-da',word_en:'to give up'},
    {word_ko:'확인하다',word_rom:'hwak-in-ha-da',word_en:'to confirm'},
    {word_ko:'후회하다',word_rom:'hu-hoe-ha-da',word_en:'to regret'},
    {word_ko:'걱정하다',word_rom:'geok-jeong-ha-da',word_en:'to worry'},
    {word_ko:'결정하다',word_rom:'gyeol-jeong-ha-da',word_en:'to decide'},
    {word_ko:'고르다',word_rom:'go-reu-da',word_en:'to choose'},
    {word_ko:'넘다',word_rom:'neom-da',word_en:'to cross, exceed'},
    {word_ko:'돌아가다',word_rom:'do-ra-ga-da',word_en:'to go back'},
    {word_ko:'떠나다',word_rom:'tteo-na-da',word_en:'to leave'},
    {word_ko:'맞다',word_rom:'mat-da',word_en:'to be correct'},
    {word_ko:'모자라다',word_rom:'mo-ja-ra-da',word_en:'to be insufficient'},
    {word_ko:'부족하다',word_rom:'bu-jok-ha-da',word_en:'to be lacking'},
    {word_ko:'복잡하다',word_rom:'bok-jap-ha-da',word_en:'complicated'},
    {word_ko:'불편하다',word_rom:'bul-pyeon-ha-da',word_en:'uncomfortable'},
    {word_ko:'심하다',word_rom:'sim-ha-da',word_en:'severe, extreme'},
    {word_ko:'익숙하다',word_rom:'ik-suk-ha-da',word_en:'familiar, used to'},
    {word_ko:'중요하다',word_rom:'jung-yo-ha-da',word_en:'important'},
    {word_ko:'특별하다',word_rom:'teuk-byeol-ha-da',word_en:'special'},
    {word_ko:'필요하다',word_rom:'pil-yo-ha-da',word_en:'necessary'},
    {word_ko:'편하다',word_rom:'pyeon-ha-da',word_en:'comfortable'},
    {word_ko:'흔하다',word_rom:'heun-ha-da',word_en:'common'},
    {word_ko:'정확하다',word_rom:'jeong-hwak-ha-da',word_en:'accurate'},
    {word_ko:'충분하다',word_rom:'chung-bun-ha-da',word_en:'sufficient'},
    {word_ko:'당연하다',word_rom:'dang-yeon-ha-da',word_en:'natural, obvious'},
    {word_ko:'신문',word_rom:'sin-mun',word_en:'newspaper'},
    {word_ko:'광고',word_rom:'gwang-go',word_en:'advertisement'},
    {word_ko:'프로그램',word_rom:'peu-ro-geu-raem',word_en:'program'},
    {word_ko:'인터넷',word_rom:'in-teo-net',word_en:'internet'},
    {word_ko:'비밀',word_rom:'bi-mil',word_en:'secret'},
    {word_ko:'분위기',word_rom:'bun-wi-gi',word_en:'atmosphere, mood'},
    {word_ko:'대부분',word_rom:'dae-bu-bun',word_en:'most, majority'},
    {word_ko:'아마',word_rom:'a-ma',word_en:'probably'},
    {word_ko:'오히려',word_rom:'o-hi-ryeo',word_en:'rather, on the contrary'},
    {word_ko:'결국',word_rom:'gyeol-guk',word_en:'in the end'},
    {word_ko:'드디어',word_rom:'deu-di-eo',word_en:'finally, at last'},
    {word_ko:'그러나',word_rom:'geu-reo-na',word_en:'however'},
    {word_ko:'따라서',word_rom:'tta-ra-seo',word_en:'therefore'},
    {word_ko:'게다가',word_rom:'ge-da-ga',word_en:'moreover'},
    {word_ko:'예를 들어',word_rom:'ye-reul deu-reo',word_en:'for example'},
    {word_ko:'마찬가지',word_rom:'ma-chan-ga-ji',word_en:'likewise'},
    {word_ko:'일단',word_rom:'il-dan',word_en:'first of all'},
    {word_ko:'제대로',word_rom:'je-dae-ro',word_en:'properly'},
    {word_ko:'점점',word_rom:'jeom-jeom',word_en:'gradually'},
    {word_ko:'미리',word_rom:'mi-ri',word_en:'in advance'},
    {word_ko:'무엇보다',word_rom:'mu-eot-bo-da',word_en:'above all'},
    {word_ko:'스트레스',word_rom:'seu-teu-re-seu',word_en:'stress'},
    {word_ko:'기분',word_rom:'gi-bun',word_en:'feeling, mood'},
    {word_ko:'용기',word_rom:'yong-gi',word_en:'courage'},
    {word_ko:'인상',word_rom:'in-sang',word_en:'impression'},
    {word_ko:'성공',word_rom:'seong-gong',word_en:'success'},
    {word_ko:'실패',word_rom:'sil-pae',word_en:'failure'},
    {word_ko:'가치',word_rom:'ga-chi',word_en:'value, worth'},
    {word_ko:'영향',word_rom:'yeong-hyang',word_en:'influence'},
    {word_ko:'소통',word_rom:'so-tong',word_en:'communication'},
    {word_ko:'발전',word_rom:'bal-jeon',word_en:'development'},
    {word_ko:'해결',word_rom:'hae-gyeol',word_en:'solution'},
    {word_ko:'증가',word_rom:'jeung-ga',word_en:'increase'},
    {word_ko:'감소',word_rom:'gam-so',word_en:'decrease'},
    {word_ko:'유지',word_rom:'yu-ji',word_en:'maintenance'},
    {word_ko:'활동',word_rom:'hwal-dong',word_en:'activity'},
    {word_ko:'참석',word_rom:'cham-seok',word_en:'attendance'},
    {word_ko:'대표',word_rom:'dae-pyo',word_en:'representative'},
    {word_ko:'전문가',word_rom:'jeon-mun-ga',word_en:'expert'},
    {word_ko:'시민',word_rom:'si-min',word_en:'citizen'},
    {word_ko:'자격',word_rom:'ja-gyeok',word_en:'qualification'},
    {word_ko:'서류',word_rom:'seo-ryu',word_en:'documents'},
    {word_ko:'계약',word_rom:'gye-yak',word_en:'contract'},
    {word_ko:'급여',word_rom:'geu-byeo',word_en:'salary'},
    {word_ko:'업무',word_rom:'eop-mu',word_en:'work, duties'},
    {word_ko:'면접',word_rom:'myeon-jeop',word_en:'interview'},
    {word_ko:'채용',word_rom:'chae-yong',word_en:'hiring'},
    {word_ko:'퇴근',word_rom:'toe-geun',word_en:'leaving work'},
    {word_ko:'출근',word_rom:'chul-geun',word_en:'going to work'},
    {word_ko:'회의',word_rom:'hoe-ui',word_en:'meeting'},
    {word_ko:'보고서',word_rom:'bo-go-seo',word_en:'report'},
    {word_ko:'마감',word_rom:'ma-gam',word_en:'deadline'},
    {word_ko:'제출',word_rom:'je-chul',word_en:'submission'},
    {word_ko:'승인',word_rom:'seung-in',word_en:'approval'},
    {word_ko:'취소',word_rom:'chwi-so',word_en:'cancellation'},
    {word_ko:'교환',word_rom:'gyo-hwan',word_en:'exchange'},
    {word_ko:'배송',word_rom:'bae-song',word_en:'delivery'},
    {word_ko:'할인',word_rom:'ha-rin',word_en:'discount'},
    {word_ko:'영수증',word_rom:'yeong-su-jeung',word_en:'receipt'},
    {word_ko:'예약',word_rom:'ye-yak',word_en:'reservation'},
    {word_ko:'접수',word_rom:'jeop-su',word_en:'reception, filing'},
    {word_ko:'신청',word_rom:'sin-cheong',word_en:'application'},
    {word_ko:'허락',word_rom:'heo-rak',word_en:'permission'},
    {word_ko:'금지',word_rom:'geum-ji',word_en:'prohibition'},
    {word_ko:'위험',word_rom:'wi-heom',word_en:'danger'},
    {word_ko:'안전',word_rom:'an-jeon',word_en:'safety'},
    {word_ko:'사고',word_rom:'sa-go',word_en:'accident'},
    {word_ko:'치료',word_rom:'chi-ryo',word_en:'treatment'},
    {word_ko:'증상',word_rom:'jeung-sang',word_en:'symptom'},
    {word_ko:'예방',word_rom:'ye-bang',word_en:'prevention'},
    {word_ko:'오염',word_rom:'o-yeom',word_en:'pollution'},
    {word_ko:'절약',word_rom:'jeol-yak',word_en:'saving, economy'},
    {word_ko:'낭비',word_rom:'nang-bi',word_en:'waste'},
    {word_ko:'적응하다',word_rom:'jeok-eung-ha-da',word_en:'to adapt'},
    {word_ko:'주장하다',word_rom:'ju-jang-ha-da',word_en:'to claim'},
    {word_ko:'반대하다',word_rom:'ban-dae-ha-da',word_en:'to oppose'},
    {word_ko:'찬성하다',word_rom:'chan-seong-ha-da',word_en:'to agree'},
    {word_ko:'존경하다',word_rom:'jon-gyeong-ha-da',word_en:'to respect'},
    {word_ko:'감동하다',word_rom:'gam-dong-ha-da',word_en:'to be moved'},
    {word_ko:'만족하다',word_rom:'man-jok-ha-da',word_en:'to be satisfied'},
    {word_ko:'대단하다',word_rom:'dae-dan-ha-da',word_en:'amazing, great'},
    {word_ko:'솔직하다',word_rom:'sol-jik-ha-da',word_en:'honest, frank'}
  ];

  var ADVANCED = [
    {word_ko:'체계',word_rom:'che-gye',word_en:'system, framework'},
    {word_ko:'구조',word_rom:'gu-jo',word_en:'structure'},
    {word_ko:'근거',word_rom:'geun-geo',word_en:'basis, grounds'},
    {word_ko:'논리',word_rom:'non-ri',word_en:'logic'},
    {word_ko:'맥락',word_rom:'maek-rak',word_en:'context'},
    {word_ko:'범위',word_rom:'beom-wi',word_en:'scope, range'},
    {word_ko:'본질',word_rom:'bon-jil',word_en:'essence'},
    {word_ko:'부담',word_rom:'bu-dam',word_en:'burden'},
    {word_ko:'사고방식',word_rom:'sa-go-bang-sik',word_en:'way of thinking'},
    {word_ko:'수단',word_rom:'su-dan',word_en:'means, measure'},
    {word_ko:'시사점',word_rom:'si-sa-jeom',word_en:'implication'},
    {word_ko:'양상',word_rom:'yang-sang',word_en:'aspect, pattern'},
    {word_ko:'여론',word_rom:'yeo-ron',word_en:'public opinion'},
    {word_ko:'요인',word_rom:'yo-in',word_en:'factor'},
    {word_ko:'원칙',word_rom:'won-chik',word_en:'principle'},
    {word_ko:'의의',word_rom:'ui-ui',word_en:'significance'},
    {word_ko:'이념',word_rom:'i-nyeom',word_en:'ideology'},
    {word_ko:'인식',word_rom:'in-sik',word_en:'awareness, perception'},
    {word_ko:'자원',word_rom:'ja-won',word_en:'resource'},
    {word_ko:'쟁점',word_rom:'jaeng-jeom',word_en:'issue, point of contention'},
    {word_ko:'절차',word_rom:'jeol-cha',word_en:'procedure'},
    {word_ko:'정책',word_rom:'jeong-chaek',word_en:'policy'},
    {word_ko:'제도',word_rom:'je-do',word_en:'system, institution'},
    {word_ko:'주장',word_rom:'ju-jang',word_en:'claim, assertion'},
    {word_ko:'취지',word_rom:'chwi-ji',word_en:'purpose, intent'},
    {word_ko:'타당성',word_rom:'ta-dang-seong',word_en:'validity'},
    {word_ko:'편견',word_rom:'pyeon-gyeon',word_en:'prejudice, bias'},
    {word_ko:'현상',word_rom:'hyeon-sang',word_en:'phenomenon'},
    {word_ko:'혁신',word_rom:'hyeok-sin',word_en:'innovation'},
    {word_ko:'합의',word_rom:'hap-ui',word_en:'agreement, consensus'},
    {word_ko:'갈등',word_rom:'gal-deung',word_en:'conflict'},
    {word_ko:'격차',word_rom:'gyeok-cha',word_en:'gap, disparity'},
    {word_ko:'고찰',word_rom:'go-chal',word_en:'examination'},
    {word_ko:'귀결',word_rom:'gwi-gyeol',word_en:'conclusion'},
    {word_ko:'기반',word_rom:'gi-ban',word_en:'foundation, base'},
    {word_ko:'대안',word_rom:'dae-an',word_en:'alternative'},
    {word_ko:'동향',word_rom:'dong-hyang',word_en:'trend'},
    {word_ko:'모순',word_rom:'mo-sun',word_en:'contradiction'},
    {word_ko:'반영',word_rom:'ban-yeong',word_en:'reflection'},
    {word_ko:'배경',word_rom:'bae-gyeong',word_en:'background'},
    {word_ko:'도출하다',word_rom:'do-chul-ha-da',word_en:'to derive'},
    {word_ko:'수반하다',word_rom:'su-ban-ha-da',word_en:'to entail'},
    {word_ko:'촉진하다',word_rom:'chok-jin-ha-da',word_en:'to promote'},
    {word_ko:'초래하다',word_rom:'cho-rae-ha-da',word_en:'to cause, bring about'},
    {word_ko:'구축하다',word_rom:'gu-chuk-ha-da',word_en:'to build, construct'},
    {word_ko:'기여하다',word_rom:'gi-yeo-ha-da',word_en:'to contribute'},
    {word_ko:'논의하다',word_rom:'non-ui-ha-da',word_en:'to discuss'},
    {word_ko:'대응하다',word_rom:'dae-eung-ha-da',word_en:'to respond'},
    {word_ko:'도모하다',word_rom:'do-mo-ha-da',word_en:'to pursue, seek'},
    {word_ko:'반박하다',word_rom:'ban-bak-ha-da',word_en:'to refute'},
    {word_ko:'보완하다',word_rom:'bo-wan-ha-da',word_en:'to supplement'},
    {word_ko:'분석하다',word_rom:'bun-seok-ha-da',word_en:'to analyze'},
    {word_ko:'수립하다',word_rom:'su-rip-ha-da',word_en:'to establish'},
    {word_ko:'시행하다',word_rom:'si-haeng-ha-da',word_en:'to implement'},
    {word_ko:'완화하다',word_rom:'wan-hwa-ha-da',word_en:'to ease, alleviate'},
    {word_ko:'적용하다',word_rom:'jeok-yong-ha-da',word_en:'to apply'},
    {word_ko:'제시하다',word_rom:'je-si-ha-da',word_en:'to present, propose'},
    {word_ko:'지적하다',word_rom:'ji-jeok-ha-da',word_en:'to point out'},
    {word_ko:'파악하다',word_rom:'pa-ak-ha-da',word_en:'to grasp, understand'},
    {word_ko:'함축하다',word_rom:'ham-chuk-ha-da',word_en:'to imply'},
    {word_ko:'검토하다',word_rom:'geom-to-ha-da',word_en:'to review, examine'},
    {word_ko:'간과하다',word_rom:'gan-gwa-ha-da',word_en:'to overlook'},
    {word_ko:'강조하다',word_rom:'gang-jo-ha-da',word_en:'to emphasize'},
    {word_ko:'고려하다',word_rom:'go-ryeo-ha-da',word_en:'to consider'},
    {word_ko:'극복하다',word_rom:'geuk-bok-ha-da',word_en:'to overcome'},
    {word_ko:'나아가다',word_rom:'na-a-ga-da',word_en:'to advance'},
    {word_ko:'뒷받침하다',word_rom:'dwit-bat-chim-ha-da',word_en:'to support, back up'},
    {word_ko:'모색하다',word_rom:'mo-saek-ha-da',word_en:'to seek, explore'},
    {word_ko:'심화되다',word_rom:'sim-hwa-doe-da',word_en:'to deepen, intensify'},
    {word_ko:'야기하다',word_rom:'ya-gi-ha-da',word_en:'to cause, provoke'},
    {word_ko:'포괄적',word_rom:'po-gwal-jeok',word_en:'comprehensive'},
    {word_ko:'근본적',word_rom:'geun-bon-jeok',word_en:'fundamental'},
    {word_ko:'객관적',word_rom:'gaek-gwan-jeok',word_en:'objective'},
    {word_ko:'주관적',word_rom:'ju-gwan-jeok',word_en:'subjective'},
    {word_ko:'보편적',word_rom:'bo-pyeon-jeok',word_en:'universal'},
    {word_ko:'획기적',word_rom:'hoek-gi-jeok',word_en:'groundbreaking'},
    {word_ko:'필연적',word_rom:'pil-yeon-jeok',word_en:'inevitable'},
    {word_ko:'지속적',word_rom:'ji-sok-jeok',word_en:'continuous'},
    {word_ko:'상대적',word_rom:'sang-dae-jeok',word_en:'relative'},
    {word_ko:'실질적',word_rom:'sil-jil-jeok',word_en:'substantial, practical'},
    {word_ko:'대대적',word_rom:'dae-dae-jeok',word_en:'large-scale'},
    {word_ko:'자발적',word_rom:'ja-bal-jeok',word_en:'voluntary'},
    {word_ko:'합리적',word_rom:'hap-ri-jeok',word_en:'rational'},
    {word_ko:'효율적',word_rom:'hyo-yul-jeok',word_en:'efficient'},
    {word_ko:'잠재적',word_rom:'jam-jae-jeok',word_en:'potential'},
    {word_ko:'즉',word_rom:'jeuk',word_en:'that is, namely'},
    {word_ko:'반면',word_rom:'ban-myeon',word_en:'on the other hand'},
    {word_ko:'더불어',word_rom:'deo-bul-eo',word_en:'along with'},
    {word_ko:'뿐만 아니라',word_rom:'ppun-man a-ni-ra',word_en:'not only'},
    {word_ko:'이에 따라',word_rom:'i-e tta-ra',word_en:'accordingly'},
    {word_ko:'한편',word_rom:'han-pyeon',word_en:'meanwhile'},
    {word_ko:'아울러',word_rom:'a-ul-reo',word_en:'in addition'},
    {word_ko:'요컨대',word_rom:'yo-keon-dae',word_en:'in short'},
    {word_ko:'다만',word_rom:'da-man',word_en:'however, but'},
    {word_ko:'과연',word_rom:'gwa-yeon',word_en:'indeed, really'},
    {word_ko:'단순히',word_rom:'dan-sun-hi',word_en:'simply, merely'},
    {word_ko:'지양하다',word_rom:'ji-yang-ha-da',word_en:'to refrain from'},
    {word_ko:'지향하다',word_rom:'ji-hyang-ha-da',word_en:'to aim for'},
    {word_ko:'담론',word_rom:'dam-ron',word_en:'discourse'},
    {word_ko:'패러다임',word_rom:'pae-reo-da-im',word_en:'paradigm'},
    {word_ko:'전환',word_rom:'jeon-hwan',word_en:'transition, shift'},
    {word_ko:'딜레마',word_rom:'dil-re-ma',word_en:'dilemma'},
    {word_ko:'메커니즘',word_rom:'me-keo-ni-jeum',word_en:'mechanism'},
    {word_ko:'거버넌스',word_rom:'geo-beo-neon-seu',word_en:'governance'},
    {word_ko:'지속가능성',word_rom:'ji-sok-ga-neung-seong',word_en:'sustainability'},
    {word_ko:'형평성',word_rom:'hyeong-pyeong-seong',word_en:'equity, fairness'},
    {word_ko:'투명성',word_rom:'tu-myeong-seong',word_en:'transparency'},
    {word_ko:'포용',word_rom:'po-yong',word_en:'inclusion'},
    {word_ko:'자율',word_rom:'ja-yul',word_en:'autonomy'},
    {word_ko:'규제',word_rom:'gyu-je',word_en:'regulation'},
    {word_ko:'협력',word_rom:'hyeop-ryeok',word_en:'cooperation'},
    {word_ko:'왜곡',word_rom:'wae-gok',word_en:'distortion'},
    {word_ko:'괴리',word_rom:'goe-ri',word_en:'discrepancy'},
    {word_ko:'함의',word_rom:'ham-ui',word_en:'implication'},
    {word_ko:'토대',word_rom:'to-dae',word_en:'foundation, basis'},
    {word_ko:'소외',word_rom:'so-oe',word_en:'alienation'},
    {word_ko:'조율',word_rom:'jo-yul',word_en:'coordination'},
    {word_ko:'이행',word_rom:'i-haeng',word_en:'fulfillment, execution'},
    {word_ko:'수렴',word_rom:'su-ryeom',word_en:'convergence'},
    {word_ko:'확산',word_rom:'hwak-san',word_en:'spread, proliferation'},
    {word_ko:'축소',word_rom:'chuk-so',word_en:'reduction, downsizing'},
    {word_ko:'재정',word_rom:'jae-jeong',word_en:'finance, fiscal'},
    {word_ko:'세율',word_rom:'se-yul',word_en:'tax rate'},
    {word_ko:'수출',word_rom:'su-chul',word_en:'export'},
    {word_ko:'수입',word_rom:'su-ip',word_en:'import'},
    {word_ko:'무역',word_rom:'mu-yeok',word_en:'trade'},
    {word_ko:'투자',word_rom:'tu-ja',word_en:'investment'},
    {word_ko:'성장률',word_rom:'seong-jang-ryul',word_en:'growth rate'},
    {word_ko:'물가',word_rom:'mul-ga',word_en:'prices, cost of living'},
    {word_ko:'실업률',word_rom:'si-reop-ryul',word_en:'unemployment rate'},
    {word_ko:'고용',word_rom:'go-yong',word_en:'employment'},
    {word_ko:'임금',word_rom:'im-geum',word_en:'wages'},
    {word_ko:'복지',word_rom:'bok-ji',word_en:'welfare'},
    {word_ko:'인권',word_rom:'in-gwon',word_en:'human rights'},
    {word_ko:'민주주의',word_rom:'min-ju-ju-ui',word_en:'democracy'},
    {word_ko:'헌법',word_rom:'heon-beop',word_en:'constitution'},
    {word_ko:'입법',word_rom:'ip-beop',word_en:'legislation'},
    {word_ko:'사법',word_rom:'sa-beop',word_en:'judiciary'},
    {word_ko:'행정',word_rom:'haeng-jeong',word_en:'administration'},
    {word_ko:'외교',word_rom:'oe-gyo',word_en:'diplomacy'},
    {word_ko:'안보',word_rom:'an-bo',word_en:'national security'},
    {word_ko:'분쟁',word_rom:'bun-jaeng',word_en:'dispute'},
    {word_ko:'조약',word_rom:'jo-yak',word_en:'treaty'},
    {word_ko:'제재',word_rom:'je-jae',word_en:'sanctions'},
    {word_ko:'선진국',word_rom:'seon-jin-guk',word_en:'developed country'},
    {word_ko:'개발도상국',word_rom:'gae-bal-do-sang-guk',word_en:'developing country'},
    {word_ko:'세계화',word_rom:'se-gye-hwa',word_en:'globalization'},
    {word_ko:'양극화',word_rom:'yang-geuk-hwa',word_en:'polarization'},
    {word_ko:'디지털화',word_rom:'di-ji-teol-hwa',word_en:'digitalization'},
    {word_ko:'탈탄소',word_rom:'tal-tan-so',word_en:'decarbonization'},
    {word_ko:'생태계',word_rom:'saeng-tae-gye',word_en:'ecosystem'},
    {word_ko:'다양성',word_rom:'da-yang-seong',word_en:'diversity'},
    {word_ko:'공정성',word_rom:'gong-jeong-seong',word_en:'fairness'},
    {word_ko:'책임',word_rom:'chaek-im',word_en:'responsibility'},
    {word_ko:'윤리',word_rom:'yun-ri',word_en:'ethics'},
    {word_ko:'배제하다',word_rom:'bae-je-ha-da',word_en:'to exclude'},
    {word_ko:'수용하다',word_rom:'su-yong-ha-da',word_en:'to accept'},
    {word_ko:'통합하다',word_rom:'tong-hap-ha-da',word_en:'to integrate'},
    {word_ko:'비판하다',word_rom:'bi-pan-ha-da',word_en:'to criticize'},
    {word_ko:'옹호하다',word_rom:'ong-ho-ha-da',word_en:'to advocate'},
    {word_ko:'위축되다',word_rom:'wi-chuk-doe-da',word_en:'to shrink, contract'},
    {word_ko:'부각되다',word_rom:'bu-gak-doe-da',word_en:'to emerge, stand out'},
    {word_ko:'선행되다',word_rom:'seon-haeng-doe-da',word_en:'to precede'},
    {word_ko:'불가피하다',word_rom:'bul-ga-pi-ha-da',word_en:'unavoidable'},
    {word_ko:'미흡하다',word_rom:'mi-heup-ha-da',word_en:'insufficient'},
    {word_ko:'방대하다',word_rom:'bang-dae-ha-da',word_en:'vast, extensive'},
    {word_ko:'치밀하다',word_rom:'chi-mil-ha-da',word_en:'thorough, meticulous'},
    {word_ko:'일관되다',word_rom:'il-gwan-doe-da',word_en:'consistent'},
    {word_ko:'심층적',word_rom:'sim-cheung-jeok',word_en:'in-depth'}
  ];

  window.LEARNING_HUB_VOCAB_DATA = {
    levels: {
      Beginner: BEGINNER,
      Intermediate: INTERMEDIATE,
      Advanced: ADVANCED
    },
    interests: {}
  };

  window.getLearningHubVocabData = function() {
    return window.LEARNING_HUB_VOCAB_DATA;
  };
})();
