-- Sample story: 사자와 생쥐 (The Lion and the Mouse)
-- Genre: aesop (Aesop's Fable) / Level: Intermediate (i / Tree)
-- Original public-domain Aesop fable, adapted into intermediate Korean.
-- Generated offline; saves into stories_data exactly like the admin's
-- "Save All to DB" button.

INSERT INTO stories_data (data, mood, lvl, title, title_en, preview, read_time, created_at)
VALUES (
  $json${
    "title": "사자와 생쥐",
    "title_en": "The Lion and the Mouse",
    "mood": "aesop",
    "genre": "aesop",
    "lvl": "i",
    "readTime": "4 min",
    "preview": "옛날 옛적에 큰 사자 한 마리가 깊은 숲속에서 살고 있었어요. 어느 날, 사자는 따뜻한 햇볕을 받으며 깊이 잠들어 있었어요.",
    "body": "옛날 옛적에 큰 사자 한 마리가 깊은 숲속에서 살고 있었어요. 어느 날, 사자는 따뜻한 햇볕을 받으며 풀밭 위에서 깊이 잠들어 있었어요.\n\n그때 작은 생쥐 한 마리가 사자의 코앞을 지나가게 되었어요. 생쥐는 사자가 거기에 있는 줄 모르고, 그만 사자의 발 위로 올라가고 말았답니다.\n\n깜짝 놀란 사자가 눈을 번쩍 떴어요. 사자는 큰 발로 작은 생쥐를 꽉 잡았어요. \"감히 나의 잠을 깨우다니!\" 사자는 큰 소리로 화를 내며 말했어요.\n\n생쥐는 너무 무서워서 떨리는 목소리로 빌었어요. \"제발 살려 주세요. 살려 주시면 언젠가 꼭 은혜를 갚을게요.\"\n\n사자는 작은 생쥐의 말을 듣고 웃음이 터졌어요. \"네가 어떻게 나를 도와줄 수 있겠니?\" 그래도 사자는 생쥐가 가엾어서 슬쩍 풀어 주었어요.\n\n며칠 후, 사자는 사냥꾼이 놓은 그물에 그만 걸리고 말았어요. 사자는 빠져나오려고 발버둥 쳤지만, 그물은 점점 더 단단하게 묶일 뿐이었어요. 사자는 절망에 빠져 크게 울부짖었어요.\n\n그 소리를 들은 작은 생쥐가 한걸음에 달려왔어요. 생쥐는 날카로운 이빨로 그물의 줄을 하나씩 하나씩 갉아 끊기 시작했어요.\n\n마침내 사자는 그물에서 빠져나올 수 있었어요. 사자는 고마운 마음으로 말했어요. \"정말 고맙다, 작은 친구야. 약한 자라도 강한 자를 도울 수 있다는 걸 오늘 배웠어.\"\n\n이 이야기의 교훈은 작고 약해 보이는 존재라도 언젠가 큰 도움이 될 수 있다는 것입니다.",
    "body_en": "Once upon a time, a great lion lived deep in the forest. One day, the lion was fast asleep on the grass, basking in the warm sunlight.\n\nJust then, a tiny mouse happened to pass right under the lion's nose. The mouse did not realize the lion was there, and ended up scampering right onto the lion's paw.\n\nStartled, the lion opened his eyes with a snap. He pinned the little mouse down with his big paw. \"How dare you wake me from my sleep!\" the lion roared in anger.\n\nThe mouse was so terrified that he pleaded in a trembling voice. \"Please spare me. If you let me go, one day I will surely repay your kindness.\"\n\nThe lion laughed out loud at the little mouse's words. \"How could you ever help me?\" Still, the lion felt sorry for the mouse and let him go.\n\nA few days later, the lion was caught in a net set by a hunter. He struggled to break free, but the net only grew tighter and tighter. In despair, the lion let out a great roar.\n\nThe little mouse heard the sound and came running in an instant. With his sharp teeth, he began to gnaw through the ropes of the net, one strand at a time.\n\nAt last, the lion was able to escape from the net. Filled with gratitude, he said, \"Thank you, little friend. Today I have learned that even the weak can help the strong.\"\n\nThe moral of this story is that even those who seem small and weak can become a great help one day.",
    "vocab": [
      {"ko":"사자","rom":"sa-ja","en":"lion"},
      {"ko":"생쥐","rom":"saeng-jwi","en":"mouse"},
      {"ko":"숲속","rom":"sup-sok","en":"deep in the forest"},
      {"ko":"햇볕","rom":"haet-byeot","en":"sunlight (warmth of)"},
      {"ko":"풀밭","rom":"pul-bat","en":"grassland, grass"},
      {"ko":"잠들다","rom":"jam-deul-da","en":"to fall asleep"},
      {"ko":"지나가다","rom":"ji-na-ga-da","en":"to pass by"},
      {"ko":"코앞","rom":"ko-ap","en":"right in front (of the nose)"},
      {"ko":"올라가다","rom":"ol-la-ga-da","en":"to climb up"},
      {"ko":"깜짝 놀라다","rom":"kkam-jjak nol-la-da","en":"to be startled"},
      {"ko":"꽉 잡다","rom":"kkwak jap-da","en":"to grip tightly"},
      {"ko":"감히","rom":"gam-hi","en":"how dare (one)"},
      {"ko":"깨우다","rom":"kkae-u-da","en":"to wake (someone) up"},
      {"ko":"화를 내다","rom":"hwa-reul nae-da","en":"to get angry"},
      {"ko":"무섭다","rom":"mu-seop-da","en":"to be scary, frightened"},
      {"ko":"떨리다","rom":"tteol-li-da","en":"to tremble"},
      {"ko":"빌다","rom":"bil-da","en":"to plead, beg"},
      {"ko":"살리다","rom":"sal-li-da","en":"to save, spare (a life)"},
      {"ko":"은혜를 갚다","rom":"eun-hye-reul gap-da","en":"to repay a kindness"},
      {"ko":"가엾다","rom":"ga-yeop-da","en":"to be pitiful"},
      {"ko":"풀어 주다","rom":"pu-reo ju-da","en":"to let go, release"},
      {"ko":"사냥꾼","rom":"sa-nyang-kkun","en":"hunter"},
      {"ko":"그물","rom":"geu-mul","en":"net"},
      {"ko":"걸리다","rom":"geol-li-da","en":"to get caught"},
      {"ko":"빠져나오다","rom":"ppa-jyeo-na-o-da","en":"to escape, get out"},
      {"ko":"발버둥 치다","rom":"bal-beo-dung chi-da","en":"to thrash about"},
      {"ko":"단단하다","rom":"dan-dan-ha-da","en":"to be firm, tight"},
      {"ko":"절망","rom":"jeol-mang","en":"despair"},
      {"ko":"울부짖다","rom":"ul-bu-jit-da","en":"to roar, wail"},
      {"ko":"달려오다","rom":"dal-lyeo-o-da","en":"to come running"},
      {"ko":"날카롭다","rom":"nal-ka-rop-da","en":"to be sharp"},
      {"ko":"이빨","rom":"i-ppal","en":"teeth"},
      {"ko":"갉다","rom":"gak-da","en":"to gnaw"},
      {"ko":"끊다","rom":"kkeun-ta","en":"to cut, sever"},
      {"ko":"마침내","rom":"ma-chim-nae","en":"finally, at last"},
      {"ko":"교훈","rom":"gyo-hun","en":"moral, lesson"},
      {"ko":"존재","rom":"jon-jae","en":"being, existence"}
    ],
    "hover_extras": [
      {"ko":"옛날 옛적에","rom":"yet-nal yet-jeo-ge","en":"once upon a time"},
      {"ko":"어느 날","rom":"eo-neu nal","en":"one day"},
      {"ko":"따뜻하다","rom":"tta-tteut-ha-da","en":"to be warm"},
      {"ko":"그때","rom":"geu-ttae","en":"at that moment"},
      {"ko":"한 마리","rom":"han ma-ri","en":"one (animal)"},
      {"ko":"제발","rom":"je-bal","en":"please (urgently)"},
      {"ko":"언젠가","rom":"eon-jen-ga","en":"someday"},
      {"ko":"꼭","rom":"kkok","en":"surely, certainly"},
      {"ko":"웃음이 터지다","rom":"u-seu-mi teo-ji-da","en":"to burst into laughter"},
      {"ko":"슬쩍","rom":"seul-jjeok","en":"quietly, casually"},
      {"ko":"며칠 후","rom":"myeo-chil hu","en":"a few days later"},
      {"ko":"점점 더","rom":"jeom-jeom deo","en":"more and more"},
      {"ko":"한걸음에","rom":"han-geo-reu-me","en":"in a single step, instantly"},
      {"ko":"하나씩","rom":"ha-na-ssik","en":"one by one"},
      {"ko":"고마운 마음","rom":"go-ma-un ma-eum","en":"a thankful heart"}
    ],
    "grammar": [
      {"pattern":"~고 있다","exp":"Progressive aspect: \"is V-ing\". <verb-stem> + 고 있다. Adds an ongoing-action layer to the verb.","ex":"깊은 숲속에서 살고 있었어요"},
      {"pattern":"~아/어 있다","exp":"Resultant state: remains in the state from a completed action. 잠들다 → 잠들어 있다 = \"is (still) asleep\".","ex":"풀밭 위에서 깊이 잠들어 있었어요"},
      {"pattern":"~게 되다","exp":"Circumstantial change: comes to / ends up. <stem> + 게 되다 marks a change of state or arrival into a situation.","ex":"사자의 코앞을 지나가게 되었어요"},
      {"pattern":"~고 말다","exp":"Unintended completion: \"ended up V-ing\". Signals that something happened despite (or against) intention.","ex":"사자의 발 위로 올라가고 말았답니다"},
      {"pattern":"~다니!","exp":"Exclamatory surprise/disbelief: \"how could (you) ~!\". Attached to verb stems to express indignation.","ex":"감히 나의 잠을 깨우다니!"},
      {"pattern":"~아/어 주다","exp":"Doing as a favor. 살리다 → 살려 주다 = \"to spare (for someone)\". 풀다 → 풀어 주다 = \"to let go (for someone)\".","ex":"제발 살려 주세요"},
      {"pattern":"~(으)ㄹ게요","exp":"Speaker's promise/intention. <stem> + (으)ㄹ게요 = \"I will (for you)\". 갚다 → 갚을게요 = \"I will repay\".","ex":"꼭 은혜를 갚을게요"},
      {"pattern":"~(으)ㄹ 수 있다","exp":"Ability/possibility. 도와주다 → 도와줄 수 있다 = \"can help\". <stem> + (으)ㄹ 수 있다 = \"can\".","ex":"네가 어떻게 나를 도와줄 수 있겠니?"},
      {"pattern":"~(으)려고 하다","exp":"Intention/attempt. 빠져나오다 → 빠져나오려고 (하다) = \"trying to escape\".","ex":"사자는 빠져나오려고 발버둥 쳤지만"},
      {"pattern":"~지만","exp":"Contrast: \"but / however\". 발버둥 쳤지만 = \"thrashed, but ~\".","ex":"발버둥 쳤지만, 그물은 점점 더 단단하게 묶일 뿐이었어요"},
      {"pattern":"~기 시작하다","exp":"Begin to V. <verb-stem> + 기 시작하다 = \"start V-ing\". 갉아 끊다 → 갉아 끊기 시작했어요.","ex":"갉아 끊기 시작했어요"},
      {"pattern":"~ㄴ/는다는 것","exp":"Nominalized reported clause: \"the fact that ~\". 도울 수 있다 → 도울 수 있다는 것 = \"the fact that (one) can help\".","ex":"도울 수 있다는 걸 오늘 배웠어"}
    ],
    "key_expressions": [
      {"ko":"옛날 옛적에","en":"once upon a time"},
      {"ko":"깊이 잠들다","en":"to be fast asleep"},
      {"ko":"깜짝 놀라다","en":"to be startled"},
      {"ko":"화를 내다","en":"to get angry"},
      {"ko":"은혜를 갚다","en":"to repay a kindness"},
      {"ko":"가엾게 여기다","en":"to take pity on"},
      {"ko":"절망에 빠지다","en":"to fall into despair"},
      {"ko":"이 이야기의 교훈은","en":"the moral of this story is"}
    ]
  }$json$::jsonb,
  'aesop',
  'i',
  '사자와 생쥐',
  'The Lion and the Mouse',
  '옛날 옛적에 큰 사자 한 마리가 깊은 숲속에서 살고 있었어요. 어느 날, 사자는 따뜻한 햇볕을 받으며 깊이 잠들어 있었어요.',
  '4 min',
  NOW()
);
