-- Add topic_writing_sentences column to study_daily_content
-- Stores pre-generated sentences for the "Build the Sentence" step in Topic Writing.
-- Format: [{ko, en, acceptable_orders, explanation}]
-- Generated by admin AI regen; editable in admin before users see them.

ALTER TABLE study_daily_content
  ADD COLUMN IF NOT EXISTS topic_writing_sentences JSONB DEFAULT '[]'::jsonb;
