-- Run this in Supabase SQL Editor (one-time backfill of new shop catalog).
-- Safe to re-run: ON CONFLICT (id) DO NOTHING skips items already present.
INSERT INTO shop_items (id, name, description, item_type, coin_price, cash_price, can_buy_with_coin, can_buy_with_cash, is_repeatable, is_active, sort_order, slug, image_url) VALUES
  ('badge_streak_warrior', 'Streak Warrior', 'For learners with a long-running daily streak.', 'profile_badge', 140, 0, true, false, false, true, 200, 'badge-streak-warrior', 'assets/shop/badge-streak-warrior.png'),
  ('badge_word_hunter', 'Word Hunter', 'Show off your growing vocabulary collection.', 'profile_badge', 120, 0, true, false, false, true, 201, 'badge-word-hunter', 'assets/shop/badge-word-hunter.png'),
  ('badge_quiz_champion', 'Quiz Champion', 'For perfect scorers and quiz devotees.', 'profile_badge', 160, 0, true, false, false, true, 202, 'badge-quiz-champion', 'assets/shop/badge-quiz-champion.png'),
  ('badge_news_junkie', 'News Junkie', 'Read 100+ articles? Wear it loud.', 'profile_badge', 140, 0, true, false, false, true, 203, 'badge-news-junkie', 'assets/shop/badge-news-junkie.png'),
  ('badge_kdrama_fan', 'K-Drama Fan', 'For fans of Korean shows & cinema.', 'profile_badge', 100, 0, true, false, false, true, 204, 'badge-kdrama-fan', 'assets/shop/badge-kdrama-fan.png'),
  ('badge_kpop_stan', 'K-Pop Stan', 'Show your K-pop fan loyalty.', 'profile_badge', 100, 0, true, false, false, true, 205, 'badge-kpop-stan', 'assets/shop/badge-kpop-stan.png'),
  ('badge_topik_chaser', 'TOPIK Chaser', 'For learners aiming at TOPIK certification.', 'profile_badge', 200, 0, true, false, false, true, 206, 'badge-topik-chaser', 'assets/shop/badge-topik-chaser.png'),
  ('badge_explorer', 'Section Explorer', 'For readers who roam every news section.', 'profile_badge', 130, 0, true, false, false, true, 207, 'badge-explorer', 'assets/shop/badge-explorer.png'),
  ('title_seed', 'Title · 새싹', 'A friendly title showing you''re just starting out.', 'profile_title', 60, 0, true, false, false, true, 220, 'title-seed', 'assets/shop/title-seed.png'),
  ('title_sprout', 'Title · 떡잎', 'Tiny sprout title for early learners.', 'profile_title', 80, 0, true, false, false, true, 221, 'title-sprout', 'assets/shop/title-sprout.png'),
  ('title_tree', 'Title · 나무', 'For solid intermediate learners.', 'profile_title', 120, 0, true, false, false, true, 222, 'title-tree', 'assets/shop/title-tree.png'),
  ('title_forest', 'Title · 숲', 'Advanced learner — you ARE the forest.', 'profile_title', 180, 0, true, false, false, true, 223, 'title-forest', 'assets/shop/title-forest.png'),
  ('title_scholar', 'Title · 학자', 'For serious students of Korean.', 'profile_title', 160, 0, true, false, false, true, 224, 'title-scholar', 'assets/shop/title-scholar.png'),
  ('title_word_master', 'Title · 단어 마스터', 'Vocabulary champion title.', 'profile_title', 140, 0, true, false, false, true, 225, 'title-word-master', 'assets/shop/title-word-master.png'),
  ('title_news_addict', 'Title · 뉴스 중독자', 'Title for the daily news binger.', 'profile_title', 120, 0, true, false, false, true, 226, 'title-news-addict', 'assets/shop/title-news-addict.png'),
  ('title_night_owl', 'Title · 야행성', 'For learners who study after midnight.', 'profile_title', 100, 0, true, false, false, true, 227, 'title-night-owl', 'assets/shop/title-night-owl.png'),
  ('title_early_bird', 'Title · 아침형 인간', 'For learners who study at dawn.', 'profile_title', 100, 0, true, false, false, true, 228, 'title-early-bird', 'assets/shop/title-early-bird.png'),
  ('title_polyglot', 'Title · Polyglot', 'You speak more than one non-native language.', 'profile_title', 140, 0, true, false, false, true, 229, 'title-polyglot', 'assets/shop/title-polyglot.png'),
  ('title_kimchi_lover', 'Title · 김치 러버', 'A fun title for Korean food fans.', 'profile_title', 90, 0, true, false, false, true, 230, 'title-kimchi-lover', 'assets/shop/title-kimchi-lover.png'),
  ('title_seoulite', 'Title · 서울러', 'For lovers of Seoul.', 'profile_title', 90, 0, true, false, false, true, 231, 'title-seoulite', 'assets/shop/title-seoulite.png'),
  ('cosmetic_aurora_frame', 'Aurora Frame', 'Northern-lights gradient profile frame.', 'profile_cosmetic', 200, 0, true, false, false, true, 240, 'cosmetic-aurora-frame', 'assets/shop/cosmetic-aurora-frame.png'),
  ('cosmetic_mint_frame', 'Mint Frame', 'Cool mint gradient frame.', 'profile_cosmetic', 140, 0, true, false, false, true, 241, 'cosmetic-mint-frame', 'assets/shop/cosmetic-mint-frame.png'),
  ('cosmetic_coral_frame', 'Coral Frame', 'Warm coral pink frame.', 'profile_cosmetic', 140, 0, true, false, false, true, 242, 'cosmetic-coral-frame', 'assets/shop/cosmetic-coral-frame.png'),
  ('cosmetic_royal_frame', 'Royal Purple Frame', 'Regal purple frame for serious learners.', 'profile_cosmetic', 220, 0, true, false, false, true, 243, 'cosmetic-royal-frame', 'assets/shop/cosmetic-royal-frame.png'),
  ('cosmetic_chuseok_frame', 'Chuseok Frame', 'Harvest moon frame for fall — limited season.', 'profile_cosmetic', 180, 0, true, false, false, true, 244, 'cosmetic-chuseok-frame', 'assets/shop/cosmetic-chuseok-frame.png'),
  ('cosmetic_seollal_frame', 'Seollal Frame', 'Lunar New Year frame with traditional motifs.', 'profile_cosmetic', 180, 0, true, false, false, true, 245, 'cosmetic-seollal-frame', 'assets/shop/cosmetic-seollal-frame.png'),
  ('cosmetic_forest_theme', 'Forest Theme', 'Calm green forest UI theme.', 'profile_cosmetic', 240, 0, true, false, false, true, 250, 'cosmetic-forest-theme', 'assets/shop/cosmetic-forest-theme.png'),
  ('cosmetic_ocean_theme', 'Ocean Theme', 'Deep blue ocean UI theme.', 'profile_cosmetic', 240, 0, true, false, false, true, 251, 'cosmetic-ocean-theme', 'assets/shop/cosmetic-ocean-theme.png'),
  ('cosmetic_paper_theme', 'Vintage Paper Theme', 'Hand-bound book aesthetic for the UI.', 'profile_cosmetic', 260, 0, true, false, false, true, 252, 'cosmetic-paper-theme', 'assets/shop/cosmetic-paper-theme.png'),
  ('reporter_tteokbokki', 'Tteokbokki', 'Spicy rice cake — newsroom favorite.', 'reporter_item', 65, 0, true, false, true, true, 260, 'reporter-tteokbokki', 'assets/shop/reporter-tteokbokki.png'),
  ('reporter_hotteok', 'Hotteok', 'Sweet pancake snack for chilly news days.', 'reporter_item', 55, 0, true, false, true, true, 261, 'reporter-hotteok', 'assets/shop/reporter-hotteok.png'),
  ('reporter_mandu', 'Mandu Plate', 'Hand-folded dumplings for the editor.', 'reporter_item', 70, 0, true, false, true, true, 262, 'reporter-mandu', 'assets/shop/reporter-mandu.png'),
  ('reporter_chimaek', 'Chimaek Combo', 'Chicken + beer — the after-work classic.', 'reporter_item', 130, 0, true, false, true, true, 263, 'reporter-chimaek', 'assets/shop/reporter-chimaek.png'),
  ('reporter_kimchi_jeon', 'Kimchi Pancake', 'Crispy kimchi pancake for rainy days.', 'reporter_item', 75, 0, true, false, true, true, 264, 'reporter-kimchi-jeon', 'assets/shop/reporter-kimchi-jeon.png'),
  ('reporter_korean_tea', 'Korean Tea Set', 'Yuja, omija, citron — pick a tea, send warmth.', 'reporter_item', 90, 0, true, false, true, true, 265, 'reporter-korean-tea', 'assets/shop/reporter-korean-tea.png'),
  ('reporter_postcard', 'Handwritten Postcard', 'Send a real handwritten thanks note.', 'reporter_item', 120, 0, true, false, true, true, 266, 'reporter-postcard', 'assets/shop/reporter-postcard.png'),
  ('reporter_polaroid', 'Polaroid Photo Pack', 'Send a polaroid photo collage to your favorite reporter.', 'reporter_item', 160, 0, true, false, true, true, 267, 'reporter-polaroid', 'assets/shop/reporter-polaroid.png'),
  ('coin_pet_kitten', 'Stripe Kitten', 'A small stripe kitten that wanders your room.', 'room_item', 90, 0, true, false, false, true, 280, 'coin-pet-kitten', 'assets/shop/coin-pet-kitten.png'),
  ('coin_pet_goldfish', 'Goldfish Bowl', 'A simple goldfish bowl with one swimming fish.', 'room_item', 70, 0, true, false, false, true, 281, 'coin-pet-goldfish', 'assets/shop/coin-pet-goldfish.png'),
  ('coin_pet_owl', 'Bookshop Owl', 'A studious owl perched on your bookshelf.', 'room_item', 120, 0, true, false, false, true, 282, 'coin-pet-owl', 'assets/shop/coin-pet-owl.png'),
  ('coin_room_telescope', 'Stargazer Telescope', 'Lean it against the window for late-night vibes.', 'room_item', 160, 0, true, false, false, true, 283, 'coin-room-telescope', 'assets/shop/coin-room-telescope.png'),
  ('coin_room_oldradio', 'Vintage Radio', 'Tunes a fictional 90s K-pop station. Decorative.', 'room_item', 100, 0, true, false, false, true, 284, 'coin-room-oldradio', 'assets/shop/coin-room-oldradio.png'),
  ('coin_room_easel', 'Painting Easel', 'A blank canvas easel — for your inner artist.', 'room_item', 130, 0, true, false, false, true, 285, 'coin-room-easel', 'assets/shop/coin-room-easel.png'),
  ('stickers_koreanfood', 'Korean Food Stickers', 'Bibimbap, kimchi, ramen — coin sticker set.', 'sticker_pack', 120, 0, true, false, false, true, 300, 'stickers-koreanfood', 'assets/shop/stickers-koreanfood.png'),
  ('stickers_studyvibes', 'Study Vibes Stickers', 'Cute study-mood stickers (hwaiting / focus / coffee).', 'sticker_pack', 120, 0, true, false, false, true, 301, 'stickers-studyvibes', 'assets/shop/stickers-studyvibes.png'),
  ('stickers_seoulscape', 'Seoul Stickers', 'Namsan tower, Han river, Gyeongbokgung sticker set.', 'sticker_pack', 140, 0, true, false, false, true, 302, 'stickers-seoulscape', 'assets/shop/stickers-seoulscape.png')
ON CONFLICT (id) DO NOTHING;
