-- Backfill of 39 new room decoration items into room_items.
-- Safe to re-run.
INSERT INTO room_items (id, name, price_nyang, image_url, base_size, effect, category, active, sort_order) VALUES
  ('modern_desk', 'Modern White Desk', 42, 'assets/room/modern-desk.png', 160, 'none', 'furniture', true, 1000),
  ('standing_desk', 'Standing Desk', 55, 'assets/room/standing-desk.png', 170, 'none', 'furniture', true, 1001),
  ('gaming_desk', 'RGB Gaming Desk', 80, 'assets/room/gaming-desk.png', 170, 'none', 'furniture', true, 1002),
  ('sofa_2seat', 'Two-Seat Sofa', 60, 'assets/room/sofa-2seat.png', 180, 'none', 'furniture', true, 1003),
  ('recliner', 'Recliner Chair', 48, 'assets/room/recliner.png', 140, 'none', 'furniture', true, 1004),
  ('bean_bag', 'Bean Bag', 22, 'assets/room/bean-bag.png', 120, 'none', 'furniture', true, 1005),
  ('kotatsu', 'Korean Kotatsu', 65, 'assets/room/kotatsu.png', 160, 'none', 'furniture', true, 1006),
  ('vanity_desk', 'Vanity Mirror Desk', 50, 'assets/room/vanity-desk.png', 150, 'none', 'furniture', true, 1007),
  ('espresso_machine', 'Espresso Machine', 32, 'assets/room/espresso-machine.png', 110, 'none', 'deco', true, 1008),
  ('vinyl_player', 'Vinyl Player', 38, 'assets/room/vinyl-player.png', 120, 'none', 'deco', true, 1009),
  ('lava_lamp', 'Lava Lamp', 18, 'assets/room/lava-lamp.png', 90, 'glow_warm', 'deco', true, 1010),
  ('moon_lamp', 'Moon Lamp', 24, 'assets/room/moon-lamp.png', 100, 'glow_warm', 'deco', true, 1011),
  ('floor_lamp', 'Floor Lamp', 26, 'assets/room/floor-lamp.png', 170, 'glow_warm', 'deco', true, 1012),
  ('aroma_diffuser', 'Aroma Diffuser', 16, 'assets/room/aroma-diffuser.png', 80, 'none', 'deco', true, 1013),
  ('humidifier', 'Humidifier', 20, 'assets/room/humidifier.png', 100, 'none', 'deco', true, 1014),
  ('wall_mirror', 'Round Wall Mirror', 28, 'assets/room/wall-mirror.png', 120, 'none', 'deco', true, 1015),
  ('whiteboard', 'Study Whiteboard', 24, 'assets/room/whiteboard.png', 160, 'none', 'deco', true, 1016),
  ('cork_board', 'Cork Pin Board', 18, 'assets/room/cork-board.png', 130, 'none', 'deco', true, 1017),
  ('map_korea', 'Map of Korea', 20, 'assets/room/map-korea.png', 150, 'none', 'deco', true, 1018),
  ('string_lights', 'String Lights', 22, 'assets/room/string-lights.png', 200, 'sparkle', 'deco', true, 1019),
  ('byobu', 'Folding Screen 병풍', 55, 'assets/room/byobu.png', 200, 'none', 'deco', true, 1020),
  ('norigae', 'Norigae 노리개', 18, 'assets/room/norigae.png', 90, 'none', 'deco', true, 1021),
  ('jangdok', 'Korean Jar 장독', 25, 'assets/room/jangdok.png', 120, 'none', 'deco', true, 1022),
  ('celadon_vase', 'Celadon 청자', 48, 'assets/room/celadon-vase.png', 110, 'none', 'deco', true, 1023),
  ('white_porcelain', 'Joseon Porcelain 백자', 45, 'assets/room/white-porcelain.png', 110, 'none', 'deco', true, 1024),
  ('maedeup', 'Korean Knot 매듭', 20, 'assets/room/maedeup.png', 100, 'none', 'deco', true, 1025),
  ('cat_white', 'White Cat', 32, 'assets/room/cat-white.png', 120, 'none', 'pet', true, 1026),
  ('cat_black', 'Black Cat', 32, 'assets/room/cat-black.png', 120, 'none', 'pet', true, 1027),
  ('corgi_dog', 'Pet Corgi', 38, 'assets/room/corgi-dog.png', 130, 'none', 'pet', true, 1028),
  ('koi_pond', 'Koi Pond', 52, 'assets/room/koi-pond.png', 160, 'none', 'pet', true, 1029),
  ('plant_pothos', 'Pothos Vine', 14, 'assets/room/plant-pothos.png', 120, 'none', 'deco', true, 1030),
  ('plant_aloe', 'Aloe Vera', 12, 'assets/room/plant-aloe.png', 90, 'none', 'deco', true, 1031),
  ('plant_orchid', 'Orchid Pot', 24, 'assets/room/plant-orchid.png', 110, 'none', 'deco', true, 1032),
  ('plant_snake', 'Snake Plant', 18, 'assets/room/plant-snake.png', 130, 'none', 'deco', true, 1033),
  ('plant_lucky_bamboo', 'Lucky Bamboo', 16, 'assets/room/plant-lucky-bamboo.png', 110, 'none', 'deco', true, 1034),
  ('xmas_tree', 'Christmas Tree', 50, 'assets/room/xmas-tree.png', 200, 'sparkle', 'deco', true, 1035),
  ('xmas_wreath', 'Christmas Wreath', 18, 'assets/room/xmas-wreath.png', 100, 'none', 'deco', true, 1036),
  ('jack_pumpkin', 'Jack O''Lantern', 14, 'assets/room/jack-pumpkin.png', 90, 'glow_warm', 'deco', true, 1037),
  ('chuseok_lantern', 'Chuseok Lantern', 24, 'assets/room/chuseok-lantern.png', 100, 'glow_warm', 'deco', true, 1038)
ON CONFLICT (id) DO NOTHING;
