-- Phase 2c (data): fill in real station names for all 6 topic lines.
-- Run AFTER 2026-04-26-topic-lines-reseed.sql.
-- Replaces placeholder names ("한글 호선 1역", etc.) with the curriculum
-- topic for that station. 50 stations × 6 lines = 300 updates in one
-- VALUES join.

update curriculum_stations s
set name_ko = v.name_ko, name_en = v.name_en
from (values
  -- ── 1호선 한글 (Hangul) ────────────────────────────────────
  (1,  1, '모음 기본',         'Vowels Basic'),
  (1,  2, '모음 응용',         'Vowels Advanced'),
  (1,  3, '자음 평음',         'Plain Consonants'),
  (1,  4, '자음 격음',         'Aspirated Consonants'),
  (1,  5, '자음 응용',         'Consonants Advanced'),
  (1,  6, '쌍자음',            'Double Consonants'),
  (1,  7, '복모음 1',          'Diphthongs 1'),
  (1,  8, '복모음 2',          'Diphthongs 2'),
  (1,  9, '받침 ㄱㄴㄷ',       'Final ㄱㄴㄷ'),
  (1, 10, '받침 ㄹㅁㅂ',       'Final ㄹㅁㅂ'),
  (1, 11, '받침 ㅅㅇㅈ',       'Final ㅅㅇㅈ'),
  (1, 12, '받침 ㅊㅋㅌㅍㅎ',   'Final ㅊㅋㅌㅍㅎ'),
  (1, 13, '겹받침 1',          'Compound Final 1'),
  (1, 14, '겹받침 2',          'Compound Final 2'),
  (1, 15, '연음법칙',          'Liaison'),
  (1, 16, '비음화',            'Nasalization'),
  (1, 17, '유음화',            'Lateralization'),
  (1, 18, '경음화',            'Tensification'),
  (1, 19, '격음화',            'Aspiration'),
  (1, 20, '구개음화',          'Palatalization'),
  (1, 21, 'ㅎ 탈락',           'ㅎ Drop'),
  (1, 22, '음절 구조',         'Syllable Structure'),
  (1, 23, '사이시옷',          'Sai-Siot'),
  (1, 24, '두음법칙',          'Initial Sound Rule'),
  (1, 25, '한자어 발음',       'Sino-Korean Pronunciation'),
  (1, 26, '외래어 표기',       'Loanword Notation'),
  (1, 27, '띄어쓰기 기본',     'Spacing Basics'),
  (1, 28, '띄어쓰기 응용',     'Spacing Applied'),
  (1, 29, '맞춤법 1',          'Spelling 1'),
  (1, 30, '맞춤법 2',          'Spelling 2'),
  (1, 31, '사투리 vs 표준어',  'Dialect vs Standard'),
  (1, 32, '한자 8급',          'Hanja Level 8'),
  (1, 33, '한자 7급',          'Hanja Level 7'),
  (1, 34, '한자 부수',         'Hanja Radicals'),
  (1, 35, '동음이의어',        'Homonyms'),
  (1, 36, '다의어',            'Polysemy'),
  (1, 37, '한자성어 1',        'Idioms 1'),
  (1, 38, '한자성어 2',        'Idioms 2'),
  (1, 39, '옛말 어휘',         'Archaic Vocabulary'),
  (1, 40, '문어체',            'Literary Style'),
  (1, 41, '한자어 조어',       'Sino-Korean Coinage'),
  (1, 42, '띄어쓰기 고급',     'Spacing Advanced'),
  (1, 43, '어원학',            'Etymology'),
  (1, 44, '학술 한자어 1',     'Academic Sino-Korean 1'),
  (1, 45, '학술 한자어 2',     'Academic Sino-Korean 2'),
  (1, 46, '신조어 표기',       'Neologism Notation'),
  (1, 47, '어문규범',          'Language Norms'),
  (1, 48, '한국어학사',        'History of Korean'),
  (1, 49, '한자 4-5급',        'Hanja Level 4-5'),
  (1, 50, '표준어 규정 종합',  'Standard Korean Comprehensive'),

  -- ── 2호선 일상대화 (Daily Conversation) ──────────────────────
  (2,  1, '인사',              'Greetings'),
  (2,  2, '자기소개',          'Self-Introduction'),
  (2,  3, '숫자',              'Numbers'),
  (2,  4, '시간/날짜',         'Time & Date'),
  (2,  5, '가족',              'Family'),
  (2,  6, '색깔/모양',         'Colors & Shapes'),
  (2,  7, '위치/방향',         'Location & Direction'),
  (2,  8, '기본 동사',         'Basic Verbs'),
  (2,  9, '쇼핑 1',            'Shopping 1'),
  (2, 10, '쇼핑 2',            'Shopping 2'),
  (2, 11, '식당 1',            'Restaurant 1'),
  (2, 12, '식당 2',            'Restaurant 2'),
  (2, 13, '카페',              'Cafe'),
  (2, 14, '길찾기',            'Asking Directions'),
  (2, 15, '대중교통',          'Public Transit'),
  (2, 16, '택시',              'Taxi'),
  (2, 17, '병원',              'Hospital'),
  (2, 18, '약국',              'Pharmacy'),
  (2, 19, '미용실',            'Hair Salon'),
  (2, 20, '은행',              'Bank'),
  (2, 21, '우체국',            'Post Office'),
  (2, 22, '편의점',            'Convenience Store'),
  (2, 23, '친구 만남',         'Meeting Friends'),
  (2, 24, '약속 잡기',         'Making Plans'),
  (2, 25, '전화 통화',         'Phone Calls'),
  (2, 26, '호텔 체크인',       'Hotel Check-in'),
  (2, 27, '집 임대',           'Renting an Apartment'),
  (2, 28, '회사 면접',         'Job Interview'),
  (2, 29, '교통사고',          'Traffic Accident'),
  (2, 30, '분실 신고',         'Lost Items Report'),
  (2, 31, '경찰 도움',         'Police Help'),
  (2, 32, '응급실',            'Emergency Room'),
  (2, 33, '인터넷 가입',       'Internet Setup'),
  (2, 34, '휴대폰 개통',       'Phone Activation'),
  (2, 35, '배달 주문',         'Delivery Order'),
  (2, 36, '세탁/수선',         'Laundry & Repair'),
  (2, 37, '갈등 해결',         'Conflict Resolution'),
  (2, 38, '사과 표현',         'Apologies'),
  (2, 39, '의견 토론',         'Opinion Debate'),
  (2, 40, '협상',              'Negotiation'),
  (2, 41, '격식 부탁',         'Formal Requests'),
  (2, 42, '우회 표현',         'Indirect Speech'),
  (2, 43, '농담/유머',         'Jokes & Humor'),
  (2, 44, '취향 설명',         'Preferences'),
  (2, 45, '심리 상태',         'Emotional States'),
  (2, 46, '추측/가능성',       'Conjecture & Possibility'),
  (2, 47, '미묘한 뉘앙스',     'Subtle Nuance'),
  (2, 48, '풍자/반어',         'Satire & Irony'),
  (2, 49, '친밀감 조절',       'Intimacy Calibration'),
  (2, 50, '세대별 말투',       'Generational Speech'),

  -- ── 3호선 K-Culture ────────────────────────────────────────
  (3,  1, '콘텐츠 인사말',     'K-Content Greetings'),
  (3,  2, '가족 호칭',         'Family Honorifics'),
  (3,  3, '음식 이름',         'Food Names'),
  (3,  4, '드라마 입문',       'K-Drama Intro'),
  (3,  5, '예능 입문',         'Variety Show Basics'),
  (3,  6, 'K-pop 가사 단어 1', 'K-pop Lyric Words 1'),
  (3,  7, 'K-pop 가사 단어 2', 'K-pop Lyric Words 2'),
  (3,  8, '콘서트 응원',       'Concert Cheers'),
  (3,  9, '드라마 명대사 1',   'Drama Famous Lines 1'),
  (3, 10, '드라마 명대사 2',   'Drama Famous Lines 2'),
  (3, 11, '사극 기초',         'Period Drama Basics'),
  (3, 12, '로맨스 드라마',     'Romance Dramas'),
  (3, 13, '학원물',            'School Dramas'),
  (3, 14, '가족 드라마',       'Family Dramas'),
  (3, 15, '예능 인사',         'Variety Greetings'),
  (3, 16, '예능 게임',         'Variety Show Games'),
  (3, 17, '먹방 어휘',         'Mukbang Vocabulary'),
  (3, 18, '여행 예능',         'Travel Variety'),
  (3, 19, '아이돌 인사말',     'Idol Greetings'),
  (3, 20, '팬덤 용어',         'Fandom Terms'),
  (3, 21, '응원봉/콘서트',     'Light-Sticks & Concerts'),
  (3, 22, '댓글 표현',         'Comment Expressions'),
  (3, 23, '드라마 갈등',       'Drama Conflicts'),
  (3, 24, '결말 패턴',         'Ending Patterns'),
  (3, 25, '사극 어법',         'Period Drama Grammar'),
  (3, 26, '가사 분석',         'Lyric Analysis'),
  (3, 27, '댄스 챌린지',       'Dance Challenges'),
  (3, 28, '인터뷰 표현',       'Interview Expressions'),
  (3, 29, '자막 읽기',         'Subtitle Reading'),
  (3, 30, '한국 영화',         'Korean Cinema'),
  (3, 31, '영화 명대사',       'Movie Famous Lines'),
  (3, 32, '웹툰 어휘',         'Webtoon Vocabulary'),
  (3, 33, '웹소설',            'Web Novels'),
  (3, 34, 'SNS',               'Social Media'),
  (3, 35, '유튜브 댓글',       'YouTube Comments'),
  (3, 36, '한국 밈',           'Korean Memes'),
  (3, 37, '사극 고어',         'Period Drama Archaic'),
  (3, 38, '시 분석',           'Poetry Analysis'),
  (3, 39, '가사 비유',         'Lyric Metaphor'),
  (3, 40, '영화 평론',         'Film Criticism'),
  (3, 41, '드라마 평론',       'Drama Criticism'),
  (3, 42, '시사 풍자',         'Current Affairs Satire'),
  (3, 43, '문학 발췌',         'Literary Excerpts'),
  (3, 44, '영화 깊이',         'Cinematic Depth'),
  (3, 45, '음악 평론',         'Music Criticism'),
  (3, 46, '비평 어휘',         'Critical Vocabulary'),
  (3, 47, '문학 작품 1',       'Literary Works 1'),
  (3, 48, '문학 작품 2',       'Literary Works 2'),
  (3, 49, '영화 학술',         'Academic Cinema'),
  (3, 50, '비평 글쓰기',       'Critical Writing'),

  -- ── 4호선 시사뉴스 (News & Society) ────────────────────────
  (4,  1, '신문 헤드라인 1',   'Headlines 1'),
  (4,  2, '헤드라인 2',        'Headlines 2'),
  (4,  3, '기본 시사 어휘',    'Basic News Vocabulary'),
  (4,  4, '일상 뉴스 어휘',    'Everyday News Vocabulary'),
  (4,  5, '날씨 뉴스',         'Weather News'),
  (4,  6, '스포츠 뉴스',       'Sports News'),
  (4,  7, '연예 뉴스',         'Entertainment News'),
  (4,  8, '사건사고',          'Incidents & Accidents'),
  (4,  9, '사회 뉴스 1',       'Society News 1'),
  (4, 10, '사회 뉴스 2',       'Society News 2'),
  (4, 11, '교육 뉴스',         'Education News'),
  (4, 12, '의료 뉴스',         'Health News'),
  (4, 13, '환경 뉴스',         'Environment News'),
  (4, 14, '경제 뉴스 입문',    'Economy News Intro'),
  (4, 15, '부동산',            'Real Estate News'),
  (4, 16, '주식 입문',         'Stock Market Intro'),
  (4, 17, '정치 입문',         'Politics Intro'),
  (4, 18, '선거 어휘',         'Election Vocabulary'),
  (4, 19, '외교 입문',         'Diplomacy Intro'),
  (4, 20, '국제 사건',         'International Events'),
  (4, 21, '기술 뉴스',         'Tech News'),
  (4, 22, '문화 뉴스',         'Culture News'),
  (4, 23, '사회 이슈 분석',    'Social Issue Analysis'),
  (4, 24, '경제 정책',         'Economic Policy'),
  (4, 25, '노동',              'Labor News'),
  (4, 26, '복지',              'Welfare News'),
  (4, 27, '정치 평론',         'Political Commentary'),
  (4, 28, '정당/이념',         'Parties & Ideology'),
  (4, 29, '외교 분석',         'Diplomatic Analysis'),
  (4, 30, '안보',              'Security News'),
  (4, 31, '국제 정세',         'International Affairs'),
  (4, 32, '환경 정책',         'Environmental Policy'),
  (4, 33, '에너지',            'Energy News'),
  (4, 34, 'M&A',               'Mergers & Acquisitions'),
  (4, 35, '금융 위기',         'Financial Crisis'),
  (4, 36, '기술 정책',         'Tech Policy'),
  (4, 37, '사설 1',            'Editorials 1'),
  (4, 38, '사설 2',            'Editorials 2'),
  (4, 39, '칼럼 1',            'Columns 1'),
  (4, 40, '칼럼 2',            'Columns 2'),
  (4, 41, '학술 시사',         'Academic Current Affairs'),
  (4, 42, '외교 학술',         'Academic Diplomacy'),
  (4, 43, '경제 학술',         'Academic Economics'),
  (4, 44, '시사 토론',         'Current Affairs Debate'),
  (4, 45, '비판적 읽기',       'Critical Reading'),
  (4, 46, '팩트체크',          'Fact-Checking'),
  (4, 47, '학술 논문',         'Academic Papers'),
  (4, 48, '정책 보고서',       'Policy Reports'),
  (4, 49, '국제 뉴스 분석',    'International News Analysis'),
  (4, 50, '시사 글쓰기',       'Op-Ed Writing'),

  -- ── 5호선 비즈니스 (Business) ───────────────────────────────
  (5,  1, '회사 인사',         'Office Greetings'),
  (5,  2, '직급 호칭',         'Job Titles'),
  (5,  3, '명함 교환',         'Business Cards'),
  (5,  4, '회사 소개',         'Company Intro'),
  (5,  5, '부서 이름',         'Department Names'),
  (5,  6, '사무실 표현',       'Office Expressions'),
  (5,  7, '출퇴근',            'Commute Talk'),
  (5,  8, '점심 약속',         'Lunch Plans'),
  (5,  9, '이메일 인사',       'Email Openings'),
  (5, 10, '이메일 본론',       'Email Body'),
  (5, 11, '이메일 마무리',     'Email Closings'),
  (5, 12, '회의 인사',         'Meeting Greetings'),
  (5, 13, '회의 발언',         'Meeting Speech'),
  (5, 14, '전화 응대',         'Phone Etiquette'),
  (5, 15, '전화 메모',         'Phone Messages'),
  (5, 16, '일정 잡기',         'Scheduling'),
  (5, 17, '약속 변경',         'Rescheduling'),
  (5, 18, '부탁/요청',         'Requests'),
  (5, 19, '거절',              'Polite Refusals'),
  (5, 20, '사과 이메일',       'Apology Emails'),
  (5, 21, '보고서 양식',       'Report Formats'),
  (5, 22, '발표 인사',         'Presentation Greetings'),
  (5, 23, '협상 1',            'Negotiation 1'),
  (5, 24, '협상 2',            'Negotiation 2'),
  (5, 25, '프레젠테이션 1',    'Presentation 1'),
  (5, 26, '프레젠테이션 2',    'Presentation 2'),
  (5, 27, '데이터 분석',       'Data Analysis'),
  (5, 28, '마케팅',            'Marketing'),
  (5, 29, '영업',              'Sales'),
  (5, 30, '기획서',            'Project Plans'),
  (5, 31, '제안서',            'Proposals'),
  (5, 32, '계약서 기본',       'Contract Basics'),
  (5, 33, '회식 매너',         'Hoesik Etiquette'),
  (5, 34, '상사 보고',         'Reporting Up'),
  (5, 35, '부하 지시',         'Delegating Down'),
  (5, 36, '갈등 조정',         'Conflict Mediation'),
  (5, 37, '협상 고급',         'Advanced Negotiation'),
  (5, 38, '계약서 고급',       'Advanced Contracts'),
  (5, 39, 'M&A 어휘',          'M&A Vocabulary'),
  (5, 40, '법무 자문',         'Legal Counsel'),
  (5, 41, '재무제표',          'Financial Statements'),
  (5, 42, '투자 보고',         'Investment Reports'),
  (5, 43, 'IR 발표',           'IR Presentations'),
  (5, 44, '글로벌 비즈니스',   'Global Business'),
  (5, 45, '국제 계약',         'International Contracts'),
  (5, 46, '비즈니스 윤리',     'Business Ethics'),
  (5, 47, '임원 보고',         'Executive Briefings'),
  (5, 48, '이사회 의사록',     'Board Minutes'),
  (5, 49, '학술 비즈니스',     'Academic Business'),
  (5, 50, 'MBA 한국어',        'MBA Korean'),

  -- ── 6호선 여행 (Travel) ─────────────────────────────────────
  (6,  1, '공항 도착',         'Airport Arrival'),
  (6,  2, '입국 심사',         'Immigration'),
  (6,  3, '짐 찾기',           'Baggage Claim'),
  (6,  4, '환전',              'Currency Exchange'),
  (6,  5, '공항→도심',         'Airport to City'),
  (6,  6, '호텔 도착',         'Hotel Arrival'),
  (6,  7, '호텔 체크인',       'Hotel Check-in'),
  (6,  8, '호텔 룸 요청',      'Room Requests'),
  (6,  9, '식당 주문',         'Ordering Food'),
  (6, 10, '카페 주문',         'Cafe Orders'),
  (6, 11, '편의점',            'Convenience Store'),
  (6, 12, '시장 흥정',         'Market Bargaining'),
  (6, 13, '백화점 환불',       'Department Returns'),
  (6, 14, '관광지 입장',       'Tourist Entries'),
  (6, 15, '사진 부탁',         'Asking for Photos'),
  (6, 16, '길 묻기',           'Asking Directions'),
  (6, 17, '지하철',            'Subway'),
  (6, 18, '버스',              'Bus'),
  (6, 19, 'KTX',               'KTX'),
  (6, 20, '추천 묻기',         'Asking Recommendations'),
  (6, 21, '카페 둘러보기',     'Cafe Hopping'),
  (6, 22, '비상상황 기본',     'Emergency Basics'),
  (6, 23, '호텔 컴플레인',     'Hotel Complaints'),
  (6, 24, '항공권 변경',       'Flight Changes'),
  (6, 25, '비자/출입국',       'Visa & Border'),
  (6, 26, '의료 응급',         'Medical Emergency'),
  (6, 27, '분실/도난',         'Lost & Theft'),
  (6, 28, '영사관',            'Consulate'),
  (6, 29, '가이드 표현',       'Tour Guide Talk'),
  (6, 30, '한옥 체험',         'Hanok Experience'),
  (6, 31, '템플 스테이',       'Temple Stay'),
  (6, 32, '등산',              'Hiking'),
  (6, 33, '스키',              'Skiing'),
  (6, 34, '해양 액티비티',     'Water Sports'),
  (6, 35, '캠핑',              'Camping'),
  (6, 36, '음식 알레르기',     'Food Allergies'),
  (6, 37, '여행 후기',         'Travel Reviews'),
  (6, 38, '여행 블로그',       'Travel Blogs'),
  (6, 39, '컴플레인 글',       'Complaint Writing'),
  (6, 40, '가이드북 어휘',     'Guidebook Vocabulary'),
  (6, 41, '여행 보험',         'Travel Insurance'),
  (6, 42, '출장',              'Business Travel'),
  (6, 43, '가족 여행',         'Family Travel'),
  (6, 44, '럭셔리',            'Luxury Travel'),
  (6, 45, '배낭여행',          'Backpacking'),
  (6, 46, '여행 사기 경계',    'Scam Awareness'),
  (6, 47, '여행 에세이',       'Travel Essays'),
  (6, 48, '여행 다큐',         'Travel Documentaries'),
  (6, 49, '문학 속 여행',      'Travel in Literature'),
  (6, 50, '여행 학술',         'Academic Travel Studies')
) as v(line_id, station_no, name_ko, name_en)
where s.line_id = v.line_id and s.station_no = v.station_no;
